### ISSUE TITLE
This looks ready for DlangScience to me

### ISSUE THREAD

**Issue by John-Colvin** [DlangScience/nlopt#1]
am I right?

**Comment by John-Colvin** [comment]
and https://github.com/dataPulverizer/glpk as well?

**Comment by dataPulverizer** [comment]
They are working but there are no tests at the moment. I can work on these libraries this weekend and prepare them for release. Is that okay?

**Comment by John-Colvin** [comment]
Yes, that would be great.

**Comment by dataPulverizer** [comment]
Library is now ready for DlangScience
